site_name: CS1 Python AI Lessons
site_url: https://anon20260930.github.io/python-skulpt-transformers
site_description: A concise description of what this project does.

theme:
  name: material
  custom_dir: overrides
  palette: 
    # This adds a toggle for light/dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode  
  features:
    # - navigation.tabs        # Top-level tabs
    # - navigation.sections    # Grouped sidebar items
    - navigation.expand
    # - search.suggest         # Smarter search
    - content.code.copy      # "Copy to clipboard" button on code blocks

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:  # This allows the use of ``` backticks
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# The structure of your site
nav:
  - LLM Strings Lessons:     
    - Introduction: lecture-09-2.md
    - Sentiment Analysis: lecture-09-3.md
    - Chatbots: lecture-09-4.md
    - Agents: lecture-09-5.md
  - Challenge / Project: 
    - Instruction: lecture-09-challenge-1.md
    - Fix Bug: lecture-09-challenge-2.md
    - Create Your Own Adventure: lecture-09-challenge-3.md
    
plugins:
  - no-sitemap
  - search:
      enabled: false
  - mkdocs_quiz:
      auto_number: true
  - revealjs:
      transition: slide
      controls: true
      history: true
      theme:
        light: solarized   # Reveal.js theme for light mode
        dark: dracula      # Reveal.js theme for dark mode
      highlight:
        light: github      # Code highlighting for light mode
        dark: github-dark  # Code highlighting for dark mode

extra:
  generator: false

# This tells MkDocs to include your custom logic on every page
extra_javascript:
  - js/custom-fullscreen.js
  - js/custom-python-embed/index.js
  - js/custom-python-embed/render-file-tree.js
  - js/custom-python-embed/render-code-editor.js
  - js/quiz-custom.js
  - js/reveal-custom.js


extra_css:
  - stylesheets/extra.css
