name: deploy-docs
on:
  push:
    branches:
      - main  
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install ProperDocs
        run: pip install properdocs mkdocs-material mkdocs-no-sitemap-plugin mkdocs-quiz mkdocs-revealjs 
      - name: Build and Deploy
        run: properdocs gh-deploy --force
